### ISSUE TITLE
How to use with the quasar framework

### ISSUE THREAD

**Issue by etewiah** [tawk/tawk-messenger-vue#10]
Hello there, would appreciate some help in using this with quasar: https://v2.quasar.dev

As per https://v2.quasar.dev/quasar-cli/boot-files I created a boot file and set it to run on the clientside only.

This is what I put in the boot file:

```
import { boot } from 'quasar/wrappers'
import TawkMessengerVue from '@tawk.to/tawk-messenger-vue'

// "async" is optional;
// more info on params: https://v2.quasar.dev/quasar-cli/boot-files
export default boot(async ({ app }) => {
  app.use(TawkMessengerVue, {
    propertyId: '**',
    widgetId: '**'
  })
})
```

I expected it would work like with nuxt but instead I got this error in the js console when I run my quasar app:

tawk-messenger-vue.js?7154:1 Uncaught (in promise) TypeError: t is not a constructor
    at Proxy.mounted (tawk-messenger-vue.js?7154:1:1)
    at callWithErrorHandling (runtime-core.esm-bundler.js?9e79:155:1)
    at callWithAsyncErrorHandling (runtime-core.esm-bundler.js?9e79:164:1)
    at Array.hook.__weh.hook.__weh (runtime-core.esm-bundler.js?9e79:2667:1)
    at flushPostFlushCbs (runtime-core.esm-bundler.js?9e79:356:1)
    at hydrate (runtime-core.esm-bundler.js?9e79:4039:1)
    at mount (runtime-core.esm-bundler.js?9e79:3873:1)
    at Object.app.mount (runtime-dom.esm-bundler.js?8886:1606:1)
    at eval (client-entry.js?2f39:134:1)

**Comment by adarshmadrecha** [comment]
If you are using Vue3, I think, the package does not work on vue 3 yet.

**Comment by etewiah** [comment]
Okay, thanks.  Any plans to support vue 3?

**Comment by adarshmadrecha** [comment]
We have moved to using direct JS (aka Script version) of tawk to library. We just have to ensure all the actions are taken only after the widget is loaded.

**Comment by jaoaustero** [comment]
@adarshmadrecha @etewiah 
Hello we understand your concern, We're very sorry on the issue that you encounter on the version 3 with this plugin.
The support for version 3 is now in progress, I will keep you up to date in this thread.

@etewiah we will provide an article for integration in Quasar after we launch this version 3

**Comment by jaoaustero** [comment]
Here's the [Version 3](https://github.com/tawk/tawk-messenger-vue-3)
