### ISSUE TITLE
Vue 3? Lol

### ISSUE THREAD

**Issue by fjeddy** [tawk/tawk-messenger-vue#11]
You release this in 2022, and it's only for Vue 2? Hahaha... Sorry, I gotta laugh, and then ask the very obvious question, when do you plan to release Vue 3? When Vue 4 comes around? 🤣 

Btw, why don't you try and install this node module with NPM ^8 and see what happens? ;)

```
At line:1 char:13
+ npm install @tawk.to/tawk-messenger-vue -S
+             ~~~~~
The splatting operator '@' cannot be used to reference variables in an expression. '@tawk' can be used only as an argument to a command. To reference variables in an expression use '$tawk'.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : SplattingNotPermitted
```

**Comment by adarshmadrecha** [comment]
I am also getting error on vue 3

**Comment by jaoaustero** [comment]
@fjeddy @adarshmadrecha 
Hello we understand your concern, We're very sorry on the issue that you encounter on the version 3 with this plugin.
The support for version 3 is now in progress, I will keep you up to date in this thread.

**Comment by ITBDarky** [comment]
If you faced the error mentioned by  [fjeddy](https://github.com/tawk/tawk-messenger-vue-2/issues/11#issue-1177629515):
```
At line:1 char:13
+ npm install @tawk.to/tawk-messenger-vue -S
+             ~~~~~
The splatting operator '@' cannot be used to reference variables in an expression. '@tawk' can be used only as an argument to a command. To reference variables in an expression use '$tawk'.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : SplattingNotPermitted
```

You can just put double quotes to wrap the package name and it will be installed successfully.
```
npm install "@tawk.to/tawk-messenger-vue"
```

**Comment by jaoaustero** [comment]
HI @ITBDarky @adarshmadrecha @fjeddy We already have support for vue 3,

Here is the packaging link https://www.npmjs.com/package/@tawk.to/tawk-messenger-vue-3
