### ISSUE TITLE
Is there any way to remove added event listener?

### ISSUE THREAD

**Issue by ITBDarky** [tawk/tawk-messenger-vue#13]
Question is as title.

How to clear unused event listener?

Example event listener below should be removed after the plugin is loaded, so I can keep my environment clean.

```
this.$tawkMessenger.$on('load', () => {
  this.$tawkMessenger.hideWidget();
});
```

**Comment by jaoaustero** [comment]
Hello @ITBDarky as of now we don't have a way to remove the event listeners. But the unused event listeners are just a small to can be ignored because it doesn't consume big resources. But we understand your concern.

I will forward this to our team and discuss it.

**Comment by jaoaustero** [comment]
@ITBDarky Hi, team decided to attach events only when it was called to avoid adding all events that some of events will be unnecessary to other users.

We don't have a way for removing the event listeners. These events are added by the messenger, and this vue wrapper/plugin is just extending it to attach callbacks provided by the users.

Changes has been filed: [https://github.com/tawk/tawk-messenger-vue-2/pull/14](https://github.com/tawk/tawk-messenger-vue-2/pull/14). I will be closing this issue.
