### ISSUE TITLE
can't install with npm

### ISSUE THREAD

**Issue by Bimman2021** [tawk/tawk-messenger-vue#17]
At line:1 char:7
+ npm i @tawk.to/tawk-messenger-react
+       ~~~~~
The splatting operator '@' cannot be used to reference variables in an expression. '@tawk' can be 
used only as an argument to a command. To reference variables in an expression use '$tawk'.       
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : SplattingNotPermitted

**Comment by jaoaustero** [comment]
Hello @Bimman2021 this repository was for vue-2 you should posting it [here](https://github.com/tawk/tawk-messenger-react/issues). Will check the issues you provided
