### ISSUE TITLE
possible to add in multiple widget id?

### ISSUE THREAD

**Issue by flabbyandroid** [tawk/tawk-messenger-vue#2]
hi im a bit new to these programming field,
and before this i used other tawk-vue plugin, and still not able to achive to set multiple widget in the vue project,
and excited to know this new plugin, still, is it even possible to set multiple widget and can change to other's widget when the project is built.
thank you in advance!

Vue.use(TawkMessengerVue, {
    propertyId : 'property_id',
    widgetId : 'widget_id'
});

**Comment by jaoaustero** [comment]
Hello @flabbyandroid 
This would be the **official plugin of Tawkto for Vue Js** but we're still on development phase.
Setting a multiple widget in single site would be impossible due to socket connections, It's only allowed
to set a single widget in each site.

But if you mean you want to change the widget base on your logic set, you should terminate the previous connection
removing the previous widget from the DOM and insert the new one.

**Comment by flabbyandroid** [comment]
> Hello @flabbyandroid This would be the **official plugin of Tawkto for Vue Js** but we're still on development phase. Setting a multiple widget in single site would be impossible due to socket connections, It's only allowed to set a single widget in each site.
> 
> But if you mean you want to change the widget base on your logic set, you should terminate the previous connection removing the previous widget from the DOM and insert the new one.

@jaoaustero thank you soo much for the clarification, it would be a hassle isn't it to do terminate the previous connection removing the widget from the DOM and inserting the new one from every client(users using my website to change the widget tawk.to) request.. but at the same time need to maintain the website not down(not restarted for every one else use the website and can use the function), hmm hahahaha im sorry if i got u confused, or even me confused

**Comment by jaoaustero** [comment]
@flabbyandroid Hello again, We do have a plan to implement called **switchWidget** It's an API that will terminate the previous widget then set a new widget by providing **property** and **widget** id. The API will the terminate the prev connection and connect the new one (new property and widget id). These will not require to restart/refresh your website. This is already been started.

**Comment by os-dlake** [comment]
> @flabbyandroid Hello again, We do have a plan to implement called **switchWidget** It's an API that will terminate the previous widget then set a new widget by providing **property** and **widget** id. The API will the terminate the prev connection and connect the new one (new property and widget id). These will not require to restart/refresh your website. This is already been started.

Was this ever completed? I am struggling with the same issue. Impossible to switch widgetId.
