### ISSUE TITLE
tawk-messenger-vue is not in npm registry.

### ISSUE THREAD

**Issue by sohaibilyas** [tawk/tawk-messenger-vue#4]
npm install tawk-messenger-vue is throwing this error:

```
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/tawk-messenger-vue - Not found
npm ERR! 404 
npm ERR! 404  'tawk-messenger-vue@*' is not in this registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
```

**Comment by jaoaustero** [comment]
Hello @sohaibilyas this is not yet released still on under development. This would be release early next year

**Comment by sohaibilyas** [comment]
@jaoaustero alright, thanks for the update.

**Comment by tbrains** [comment]
hey, any updates on the release?

Thanks

**Comment by jaoaustero** [comment]
@tbrains Hello we're still doing the testing before we deploy it. Our possible date to release by 2nd week of January

**Comment by tbrains** [comment]
@jaoaustero, thanks for the update.

**Comment by jaoaustero** [comment]
@tbrains @sohaibilyas Hello it's now live on NPM https://www.npmjs.com/package/@tawk.to/tawk-messenger-vue
