### ISSUE TITLE
Multiple Console Log 

### ISSUE THREAD

**Issue by saimonx** [tawk/tawk-messenger-vue#8]
Hello.

Is needed to make 69 console.log with the word "tawk.to" when the plugin is loading?

Is there any way to don't make it?

<img width="1675" alt="Captura de pantalla 2022-03-05 a las 13 53 25" src="https://user-images.githubusercontent.com/546832/156883986-ff8be559-b7c1-4deb-8eaa-98b5566ac833.png">

Thank You

**Comment by jaoaustero** [comment]
Thank you @saimonx for reporting the issue. This was already fixed.
It will be published to the NPM next week.

**Comment by jaoaustero** [comment]
@saimonx Hi, We already update the package on NPM.
